### ISSUE TITLE
module 'esm' has no attribute 'pretrained'

### ISSUE THREAD

**Issue by agarrubio** [PeptoneLtd/ADOPT#40]
Instalation worked without problems.

Why do I get that message when I run the example code?:
```
from adopt import MultiHead, ZScorePred

# Prepare protein sequence and name i.e brmid
SEQUENCE = "SLQDGVRQSRASDKQTLLPNDQLYQPLKDREDDQYSHLQGNQLRRN"
PROTID = "Protein 18890"

# Choose model type and training strategy
MODEL_TYPE = "esm-1b"
STRATEGY = "train_on_cleared_1325_test_on_117_residue_split"

# Extract residue level representations
multi_head = MultiHead(MODEL_TYPE)  # ***** FAILS at this point *****
```

**Comment by fabio-peptone** [comment]
Hi @agarrubio . We use ESM as a git submodule, and I believe the installation of that submodule might have failed at some point. 
I just tried installing in a brand new conda environment and tested your code without issues. 

You could try the following (feel free to use python venvs instead of conda if you wish)
```
$ conda create -n tmp-adopt
$ conda activate tmp-adopt
$ pip3 install \ 
  pandas \
  fair-esm \
  biopython \
  bertviz \
  skl2onnx \
  onnxruntime \
  spacy \
  plotly \
  wandb \
  jupyterlab
$ git clone https://github.com/PeptoneInc/ADOPT.git
$ cd ADOPT
$ git submodule update --init --recursive
$ python setup.py install
```

We currently do not include instructions on how to install prerequisites, I'll update the readme as a follow up to this issue
